config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  #Oauth
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]

  get '/log_out' => 'sessions#destroy', as: 'logout'

  get '/users/:id/settings' => 'users#settings', as: 'settings'
  patch '/users/:id/settings' => 'users#update_settings'

  #scope methods
  get '/users/:id/stations/residential' => "stations#residential"

  #check is stations in zip have changed
  get '/stations/check_for_updates' => 'stations#check_for_updates'
  get '/stations/search' => 'stations#search', as: 'search'

  resources :sessions, only: [:new, :create]

  resources :users, except: [:index] do
    resources :stations, only: [:index, :new, :create]
  end
  resources :stations, only: [:show] do
    resources :notes, only: [:create, :destroy]
  end

  #add and remove associations of user to station
  get '/users/:user_id/stations/:id' => 'users_stations#create', as: 'add_station'
  patch '/users/:user_id/stations/:id' => 'users_stations#update', as: 'add_date_station'
  delete '/users/:user_id/stations/:id/delete' => 'users_stations#destroy', as: 'remove_station'

end

app/models/station.rb
class Station < ApplicationRecord
    has_many :users_station
    has_many :users, through: :users_station
    has_many :notes
    validates :name, presence: true
    validates :zip, presence: true, length: {is: 5}
    validates :address, presence: true
    validates :access, presence: true

    scope :residential, -> {where(access: 'residential')}
    #add more complex scope methods
end

app/controllers/stations_controller.rb
require_relative './api_controller.rb'

class StationsController < ApplicationController

    def index
        @user = current_user
        @users_stations = UsersStation.where(user_id: current_user.id)
        @stations = @user.stations
        render '/users/users_stations'
    end

    def show 
        @user = current_user
        @station = Station.find_by(id:params[:id])
        @user_count = @station.users.count
        @station_notes = @station.notes
        render '/stations/show'
    end

    def residential
        @user = current_user
        @stations =  Station.where(zip: @user.zip).residential
        @message = "Displaying Residential Stations in #{@user.zip}"
        render '/users/show'
    end

    def new
        @station = Station.new
    end

    def create
        @station = current_user.stations.build(
            name: params[:station][:name],
            city: params[:station][:city],
            state: params[:station][:state],
            zip: params[:station][:zip],
            address: params[:station][:address],
            phone: params[:station][:phone],
            ELEC: true,
            status: "Pending Approval",
            access: "residential",
            flagged: true,
            updates: false
        )
        
        if @station.save
            redirect_to user_path(current_user)
        else    
           render :new
        end
    end

    def search
        @stations = ApiController.create_station_objects(params[:zip], ApiController.get_stations_from_zip(params[:zip]))
        render '/stations/search'
    end

    def check_for_updates
        #use ['id'] for new_stations, and api_id for stations in the DB
        user = current_user
        current_stations = Station.where(zip: user.zip)
        new_stations = ApiController.get_stations_from_zip(user.zip)
    
        if current_stations.count != new_stations.count
            #station in our DB no longer in API
            if new_stations.count < current_stations.count
                current_stations.each do |station|
                    
                    if !new_stations.select{|s| s['id'] == station.api_id}.any?

                        if station.access == "residential"

                            if station.flagged
                                @message = "#{station.name} Residential Station, is pending approval for public use."
                            else
                                @message = "#{station.name} Residential Staition, is availible for public use!"
                            end
                            render "/stations/check_for_updates"
                            
                        else
                            @message = "#{station.name}, has been removed."
                            station.destroy
                            render "/stations/check_for_updates"
                        end
                    end

                end
            #new station found in API
            elsif new_stations.count > current_stations.count
                new_stations.each do |station|
                    
                    if current_stations.find_by(api_id: station['id']).nil?
                        @message = "#{station['station_name']}, has been added in your area!."
                        ApiController.create_station(station)
                        render "/stations/check_for_updates"
                    end

                end
            end
        else
            @message = "No updates in your home zip."
            render "/stations/check_for_updates"
        end
    end

end

app/views/stations/_errors.html.erb
<% if @station.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@station.errors.count, "error") %> prohibited this station from being saved:</h2>

    <ul>
      <% @station.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/stations/check_for_updates.html.erb
<h1><%= link_to @message, :back %></h1>


app/views/stations/new.html.erb
<h1>Create a New Residential Station</h1>

<%= render "errors" %>

<div id="card_container">

    <%= form_for :station, url: user_stations_path(current_user) do |f|%>

        <%= f.label "Name *" %><br>
        <%= f.text_field :name, required: true %><br>

        <%= f.label :city %><br>
        <%= f.text_field :city %><br><br>

        <%= f.label :state %><br>
        <%= f.text_field :state %><br><br>

        <%= f.label "Zip *" %><br>
        <%= f.text_field :zip, placeholder: "5-digit zip", required: true %><br><br>

        <%= f.label "Address *" %><br>
        <%= f.text_area :address, placeholder:"1234 S James St", required: true %><br><br>

    <!--value added to prevent default N/A as placeholder-->
        <%= f.label :phone %><br>
        <%= f.text_field :phone, value: "", placeholder: "(xxx)xxx-xxxx",required: true %><br><br>
    <div class='buttons'>
        <%= f.submit "Create Residential Station", class: 'btn btn-primary'%>
    </div>
    <%end%>
</div>

app/views/stations/search.html.erb
<h1> Search </h1>
<%= link_to "Show all #{current_user.name}'s stations", user_stations_path(current_user), class:'btn btn-primary' %>
<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Access</th>
    <th>Link</th>
    <th>Add Station</th>
  </tr>
  <% if @stations.any? %>
    <% @stations.each do |s| %>
      <tr>
          <td>
              <%= s.name %>
          </td>
          <td>
              <%= "#{s.address}, #{s.city}, #{s.state}, #{s.zip}" %>
          </td>
          <td>
              <%= s.access %>
          </td>
          <td>
             <%= link_to "Show #{s.name}", station_path(s)%>
          </td>
          <td>
          <!---show add only if user doesn't already have station saved--->
             <%= link_to "Add to Your Stations", add_station_path(current_user, s), class:'btn btn-primary' %>
          </td>
      </tr>
    <% end %>
  <% end %>
</table>

app/views/stations/show.html.erb
<h3><%= @user_count %> users have this station saved</h3>

<div id='card_container'>

   <h3><%= @station.name %></h3><br>
   <p>Address: <%= @station.address %></p>
   <p>City: <%= @station.city %></p>
   <p>State: <%= @station.state %></p>
   <p>Zip: <%= @station.zip %></p>
   <p>Status: <%= @station.status %></p><br>
   <p>Phone Number: <%= @station.phone %></p>

   <p>Notes:</p>
   <ul id='notes'>
   <% @station_notes.each do |n| %>
        <li>
        <div class='note'>
            <p> <%= n.content %> </p>
            <% if n.user ==  @user %>
               <%= button_to 'remove', station_note_path(@station.id, n.id), method: 'delete', id:'remove_note' %>
               <% else %>
               <%= "created by: #{n.user.name}" %>
            <% end %>
         </div>
        </li>
   <% end %>
   </ul>
   
   <%= form_with url: station_notes_path(@station) do |f| %>
   <%= hidden_field_tag :note, :station_id, value: @station.id %>
   <%= f.text_area :content %>
   
   <div class='buttons'>
      <%= submit_tag 'Add Note', class: 'btn btn-primary' %>
      <% end %>
      <% if @station.users.find_by(id: @user.id) %>
         <%= button_to 'Remove Station', remove_station_path(@user, @station), method: 'delete', class: 'btn btn-danger' %>
      <% end %>
   </div>
   
</div>