config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  #Oauth
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]

  get '/log_out' => 'sessions#destroy', as: 'logout'

  get '/users/:id/settings' => 'users#settings', as: 'settings'
  patch '/users/:id/settings' => 'users#update_settings'

  #scope methods
  get '/users/:id/stations/residential' => "stations#residential"

  #check is stations in zip have changed
  get '/stations/check_for_updates' => 'stations#check_for_updates'
  get '/stations/search' => 'stations#search', as: 'search'

  resources :sessions, only: [:new, :create]

  resources :users, except: [:index] do
    resources :stations, only: [:index, :new, :create]
  end
  resources :stations, only: [:show] do
    resources :notes, only: [:create, :destroy]
  end

  #add and remove associations of user to station
  get '/users/:user_id/stations/:id' => 'users_stations#create', as: 'add_station'
  patch '/users/:user_id/stations/:id' => 'users_stations#update', as: 'add_date_station'
  delete '/users/:user_id/stations/:id/delete' => 'users_stations#destroy', as: 'remove_station'

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :users_station
    has_many :stations, through: :users_station
    has_many :notes
    # make custom validation for zip if not omniauth login
    # validates :zip, length: {is: 5}, numericality: true



    def self.from_omniauth(auth_hash)
        user = User.find_or_create_by(email: auth_hash['info']['email'])
        if user.id.nil?
            user.name = auth_hash['info']['name']         
            user.password = SecureRandom.hex(10)
            user.save
            user
        else
            user
        end
    end
end

app/controllers/users_controller.rb
require_relative './api_controller.rb'

class UsersController < ApplicationController
    skip_before_action :require_login, only: [:new, :create]

    def new
        if user_signed_in?
            redirect_to user_path(current_user)
        else
            @user = User.new
            render :new
        end
    end

    def create
        @user = User.new(user_params)

        if @user.save
            session[:user_id] = @user.id
            if !@user.zip.nil?
                ApiController.create_station_objects(@user.zip, ApiController.get_stations_from_zip(@user.zip))
            end
            redirect_to user_path(@user)
        else
            render :new
        end
    end

    def show
        @user = current_user
        if !@user.zip.nil?
            stations = Station.where(zip: @user.zip)
            if stations.empty?
                stations = ApiController.create_station_objects(@user.zip, ApiController.get_stations_from_zip(@user.zip))
            end
            @stations = []
        
                stations.each do |s|
                    if check_settings(s, @user)
                    @stations << s
                end
            end
            @stations
        else
            @stations = []
            flash.now[:alert] = "Go to settings to set your home zip."
        end
    end

    def update
        user = current_user
        email = params[:user][:email]
        password = params[:user][:password]

        if email != ""
            user.update(email: email)
        end
        if password != ""
            user.update(password: password)
        end
        
        redirect_to edit_user_path(user), alert: "User updated"
    end
    
    def destroy
        User.find(current_user.id).destroy
        redirect_to new_user_path
    end

    def settings
        @user = current_user
        render '/users/settings'
    end

    def check_settings(station, user)
       if (station.zip == user.zip &&
           station.ELEC == user.ELEC && 
           station.BD == user.BD && 
           station.CNG == user.CNG && 
           station.LPG == user.LPG && 
           station.LNG == user.LNG && 
           station.HY == user.HY && 
           station.E85 == user.E85)
            true
       else 
            false
       end
    end

    def update_settings
        user = current_user
        user.update(settings_params)

        ApiController.create_station_objects(user.zip, ApiController.get_stations_from_zip(user.zip))

        redirect_to user_path(user.id)
    end

    private 

    def user_params
        params.require(:user).permit(:name, :zip, :email, :password)
    end

    def settings_params
        params.require(:user).permit(
            :name,
            :zip,
            :BD,
            :ELEC,
            :CNG,
            :E85,
            :HY,
            :LNG,
            :LPG
        )

    end
end

app/views/users/edit.html.erb
<div id="card_container">

    <h1>Edit User</h1>
    <%= form_for :user, url: user_path(current_user), :method => :patch do |f|%>
    
        <%= f.label :email %><br>
        <%= f.email_field :email, value: current_user.email %><br>
    
        <%= f.label :password %><br>
        <%= f.password_field :password %><br>

    <div class="buttons">
        <%= f.submit "Update User", class: 'btn btn-primary'%>
    </div>

    <%end%>
    
    <div class="buttons">
        <%= button_to "Delete Account", user_path(current_user), :method => :delete, class: 'btn btn-danger'%>
    </div>

</div>

app/views/users/new.html.erb
<div id="card_container">

    <h1>Sign Up</h1>
    
    <%= form_for :user, url: users_path do |f|%>
        <%= f.label :name %><br>
        <%= f.text_field :name, required: true%><br>
    
        <%= f.label :zip %><br>
        <%= @user.errors.full_messages_for(:zip)[0] if @user.errors.any? %>
        <%= f.text_field :zip, required: true %><br>
    
    
        <%= f.label :email %><br>
        <%= f.email_field :email, required: true %><br>
    
        <%= f.label :password %><br>
        <%= f.password_field :password, required: true %><br>
    <div class='buttons'>
        <%= f.submit "Sign Up", class: 'btn btn-primary'%>
    </div>
    <%end%>
    <div class='buttons'>
        <%= button_to "Login with GitHub", '/auth/github', class: 'btn' %>
    </div>
</div>

app/views/users/settings.html.erb
<h1><%= current_user.name %>'s Settings</h1>

<div id="card_container">

    <%= form_for :user, method: :patch do |f|%>

        <%= f.label :name %><br>
        <%= f.text_field :name%><br>

        <%= f.label "Change Home Zip Code" %><br>
        <%= f.text_field :zip %><br><br>

        <h4><strong>Select Fuel Options Below</strong></h4><br>

        <%= f.label "Electric" %>
        <%= f.check_box :ELEC %><br>
        <%= f.label "Biodisel" %>
        <%= f.check_box :BD %><br>
        <%= f.label "Compressed Natural Gas" %>
        <%= f.check_box :CNG %><br>
        <%= f.label "E85" %>
        <%= f.check_box :E85 %><br>
        <%= f.label "Hydrogen" %>
        <%= f.check_box :HY %><br>
        <%= f.label "Liquefied Natural Gas" %>
        <%= f.check_box :LNG %><br>
        <%= f.label "Propane" %>
        <%= f.check_box :LPG %><br><br>

        <%= f.submit "Update Settings", class: 'btn btn-primary'%>
    <%end%>
    <%= link_to "Change Email/Password, or Cancel your acount", edit_user_path %>
</div>

app/views/users/show.html.erb
<h1>Welcome, <%= @user.name %>!</h1>
<% if @message %>
  <h4><%= @message %></h4>
<% else %>
  <h4> You have <%= @stations.count %> stations in your zip.</h4>
<% end %>

<%= link_to "Show all #{@user.name}'s stations", user_stations_path(@user), class:'btn btn-primary' %>
<%= link_to "Check for Updates", stations_check_for_updates_path, class:'btn btn-warning' %>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Access</th>
    <th>Link</th>
    <th>Add Station</th>
  </tr>
  <% @stations.each do |s|%>
    <tr>
        <td>
            <%= s.name %>
        </td>
        <td>
            <%= "#{s.address}, #{s.city}, #{s.state}, #{s.zip}" %>
        </td>
        <td>
            <%= s.access %>
        </td>
        <td>
           <%= link_to "Show #{s.name}", station_path(s)%>
        </td>
        <td>
        <!---show add only if current_user doesn't already have station saved--->
           <%= link_to "Add to Your Stations", add_station_path(current_user, s), class:'btn btn-primary' %>
        </td>
    </tr>
  <% end %>
</table>

app/views/users/users_stations.html.erb
<h1>Welcome, <%= current_user.name %>!</h1>
<h4> You have <%= @stations.count %> stations saved.</h4>
<%= link_to "Show stations near #{current_user.name}", user_path(current_user), class:'btn btn-primary' %>
<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Access</th>
    <th>Link</th>
    <th>Visited</th>
  </tr>
  <% @stations.each do |s|%>
    <tr>
        <td>
            <%= s.name %>
        </td>
        <td>
            <%= "#{s.address}, #{s.city}, #{s.state}, #{s.zip}" %>
        </td>
        <td>
            <%= s.access %>
        </td>
        <td>
           <%= link_to "Show #{s.name}", station_path(s.id) %>
        </td>
        <td>
        <% if @users_stations.find_by(station_id: s.id).date_visited.nil? %>
            <%= form_tag add_date_station_path(id: s.id), method: :patch %>
            <%= hidden_field :date_visited, :station_id, value: s.id %>
            <%= label_tag :date_visited %>
            <%= text_field_tag :date_visited %>
            
            <div class='buttons'>
               <%= submit_tag "Update", class: 'btn btn-primary'%>
            </div>
            <% else %>
              <%= @users_stations.find_by(station_id: s.id).date_visited %>
            <% end %>
        </td>
    </tr>
  <% end %>
</table>