config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  #Oauth
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]

  get '/log_out' => 'sessions#destroy', as: 'logout'

  get '/users/:id/settings' => 'users#settings', as: 'settings'
  patch '/users/:id/settings' => 'users#update_settings'

  #scope methods
  get '/users/:id/stations/residential' => "stations#residential"

  #check is stations in zip have changed
  get '/stations/check_for_updates' => 'stations#check_for_updates'
  get '/stations/search' => 'stations#search', as: 'search'

  resources :sessions, only: [:new, :create]

  resources :users, except: [:index] do
    resources :stations, only: [:index, :new, :create]
  end
  resources :stations, only: [:show] do
    resources :notes, only: [:create, :destroy]
  end

  #add and remove associations of user to station
  get '/users/:user_id/stations/:id' => 'users_stations#create', as: 'add_station'
  patch '/users/:user_id/stations/:id' => 'users_stations#update', as: 'add_date_station'
  delete '/users/:user_id/stations/:id/delete' => 'users_stations#destroy', as: 'remove_station'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AltFuelStationsDvb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

      <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
          <div class="navbar-header">
          <a class= "navbar-brand" href="<%=user_path(current_user) %>"/> Alt Fuel Stations </a>
          </div>
          <ul class="nav navbar-nav">
            <% if user_signed_in? %>
            <li>
              <a href="<%= user_stations_path(current_user) %>"/>Home</a>
            </li>
             <li>
              <a href="<%= user_path(current_user) %>"/>Stations Near You</a>
            </li>
             <li>
              <a href="<%= new_user_station_path(current_user) %>"/>Create Station</a>
            </li>
            <li>
              <a href="<%= settings_path(current_user) %>"/>Settings</a>
            </li>
            <li>
              <a href="<%= logout_path %>" />Log Out</a>
            </li>
          </ul>
            <form class="navbar-form navbar-right" action= <%= search_path %>>
            <input class="form-control" type="search" name="zip" placeholder="Zip Code">
            <button class="btn" type="submit">Search</button>
            </form>
            <% else %>
            <li>
              <a href="<%= new_session_path %>">Login</a>
            </li>
            <li>
              <a href="<%= new_user_path %>">Sign Up</a>
            </li>
          </ul>

            <% end %>
      </div>
    </div>
  <!-- content -->
  <div id="flash_message">
   <% if flash[:alert] %>
      <div class="alert">
        <%= flash[:alert] %>
      </div>
    <% end %>
  </div>

    <%= yield %>

  </body>
</html>